version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: giphy-api-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - giphy-api-network
    ports:
      - "9000:9000"
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: giphy-api-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: giphy_api
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - giphy-api-network

networks:
  giphy-api-network:
    driver: bridge

volumes:
  db_data:
