version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: PrexPHPChallenge-Sepulveda-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - PrexPHPChallenge-Sepulveda-network
    ports:
      - "9000:9000"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: PrexPHPChallenge-Sepulveda-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: prexchallenge
      MYSQL_USER: juansepu96
      MYSQL_PASSWORD: 2gc)EwXym-l_MChR
      MYSQL_ROOT_PASSWORD: 
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - PrexPHPChallenge-Sepulveda-network

networks:
  PrexPHPChallenge-Sepulveda-network:
    driver: bridge

volumes:
  db_data:
